# Site settings
title: qianze zhang
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  qianze zhang | young artist and writer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: QlANZEZHANG
github_username:  qianze

# Build settings
markdown: kramdown
permalink: pretty
